version: "3"

services:
  verdaccio:
    image: verdaccio/verdaccio:5
    ports:
      - "4873:4873"
    expose:
      - "4873"
    volumes:
      - ./verdaccio/storage:/verdaccio/storage
      - ./verdaccio/failing-conf:/verdaccio/conf
    networks:
      - verdaccio_net

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - verdaccio
    networks:
      verdaccio_net:
        aliases:
          - registry.local

networks:
  verdaccio_net:
    external: true
